server:
  port: 19095

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/eleven-logistics-order
    username: eleven-logistics
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

  rabbitmq:
    host: 129.154.192.198
    port: 5672
    username: eleven-logistics
    password: eleven-logistics

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

# [Order Service]
message:
  send:
    exchange: order
    queue:
      delivery: order.delivery

# [Error Handling for Order Service]
    err:
      exchange: order.err
      queue:
        delivery: order.err.delivery

# [Delivery Service]
  receive:
    queue:
      order: delivery.order

# [Error Handling for Delivery Service]
    err:
      exchange: delivery.err
      queue:
        order: delivery.err.order